GET  http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImVtYWlsIjoiZW1haWxAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjIxMTU0NzUsImV4cCI6MTcyMjExOTA3NX0.wijRJvhINGHmGIgpnkurx8w23GH4fDaoYwpA9PzgBBI

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "username": "test",
    "password": "1213",
    "confPassword": "1213",
    "email": "email@example.com",
    "id_unit": null,
    "role": "admin"
}

###
POST  http://localhost:5000/users/login
Content-Type: application/json

{
    "emailOrUsername": "test",
    "password": "1213"
}

###
GET http://localhost:5000/token

###
GET http://localhost:5000/logout