GET  http://localhost:5000/users/454407b6-201d-41ef-9fda-5370d7b9f0d0

###
POST  http://localhost:5000/users/create
Content-Type: application/json

{
    "username": "admin",
    "password": "12",
    "confPassword": "12",
    "email": "admin@gmail.com",
    "role": "admin"
}


###
POST  http://localhost:5000/users/create
Content-Type: application/json

{
    "username": "kesehatan",
    "password": "12",
    "confPassword": "12",
    "email": "hukum@gmail.com",
    "role": "user",
    "nama_unit": "kesehatan",
    "alamat": "kota"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "12"
}

### cek login 
GET http://localhost:5000/userOn/

###
DELETE http://localhost:5000/logout

### Admin
PATCH  http://localhost:5000/users/update/454407b6-201d-41ef-9fda-5370d7b9f0d0
Content-Type: application/json

{
    "username": "kesehatan",
    "password": "12",
    "confPassword": "12",
    "email": "newemail@example.com",
    "role": "user",
    "unit_kerjas": [
        {
            "nama_unit": "UpdatedNamaUnit",
            "alamat": "UpdatedAlamat"
        }
    ]
}

###
GET  http://localhost:5000/unit

### cek survey 
GET http://localhost:5000/survey/

### cek survey 


###
DELETE http://localhost:5000/akun/cfdce369-ccc2-425c-92f8-18f4ed6a59ca