### login user
POST  http://localhost:5000/login
Content-Type: application/json

{
    "username": "hukum",
    "password": "1213"
}

### cek login
GET http://localhost:5000/userOn/

###
DELETE http://localhost:5000/logout

### getLayanan all or id
GET  http://localhost:5000/layanan/61a1e81e-9f8c-47e1-83f7-e70ca7402540

###
POST   http://localhost:5000/layanan
Content-Type: application/json

{
    "nama_layanan": "parkir"
}

###
PATCH http://localhost:5000/layanan/61a1e81e-9f8c-47e1-83f7-e70ca7402540
Content-Type: application/json

{
    "nama_layanan": "dokter12"
}

###
DELETE http://localhost:5000/layanan/13905f01-62ef-4be6-9040-4a19fb5d9db4