### login user
POST  http://localhost:5000/login
Content-Type: application/json

{
    "username": "kesehatan",
    "password": "12"
}

### cek login
GET http://localhost:5000/userOn/

###
DELETE http://localhost:5000/logout

### getLayanan all or id
GET  http://localhost:5000/layanan/

###
POST   http://localhost:5000/layanan
Content-Type: application/json

{
    "nama_layanan": "parkir"
}

###
PATCH http://localhost:5000/layanan/d4ff7353-a1b3-433f-b927-75ce64d2401b
Content-Type: application/json

{
    "nama_layanan": "dokter12"
}