### cek survey 
GET  http://localhost:5000/survey/

### cek survey 
GET  http://localhost:5000/survey/2b9c111d-22dc-46c6-8431-42deca0cf677

### Bikin survey
POST  http://localhost:5000/survey/create
Content-Type: application/json

{
    "url": "kesehatan1",
    "judul": "Jombang08/24",
    "pertanyaan": ["Apa kabar?", "Harimu gimana?"]
}

### cek survey 
DELETE http://localhost:5000/survey/delete/91df9f2d-b48e-43ac-8201-33465ddd7d88