### cek survey 
GET  http://localhost:5000/survey/

### cek survey 
GET  http://localhost:5000/survey/

### Bikin survey
POST  http://localhost:5000/survey/create
Content-Type: application/json

{
    "url": "kesehatan1",
    "judul": "Jombang08/24",
    "pertanyaan": ["Apa kabar?", "Harimu gimana?"]
}

### cek survey 
DELETE http://localhost:5000/survey/delete/e8c9c4d0-2f53-407e-b867-4036db7b0511